---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	seo_blog_writer(seo_blog_writer)
	seo_tools(seo_tools)
	x_writer(x_writer)
	x_tools(x_tools)
	general_handler(general_handler)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	router -.-> general_handler;
	router -.-> seo_blog_writer;
	router -.-> x_writer;
	seo_blog_writer -.-> __end__;
	seo_blog_writer -. &nbsp;tools&nbsp; .-> seo_tools;
	seo_tools --> seo_blog_writer;
	x_tools --> x_writer;
	x_writer -.-> __end__;
	x_writer -. &nbsp;tools&nbsp; .-> x_tools;
	general_handler --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
